language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
gemfile:
  - gemfiles/Gemfile.rails3_1
  - gemfiles/Gemfile.rails3_2
  - gemfiles/Gemfile.rails4_0
exclude:
  - rvm: 1.8.7
    gemfile: gemfiles/Gemfile.rails4_0
  - rvm: jruby-18mode
    gemfile: gemfiles/Gemfile.rails4_0
  - rvm: rbx-18mode
    gemfile: gemfiles/Gemfile.rails4_0
