language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-18mode
  - rbx-19mode
gemfile:
  - gemfiles/Gemfile.rails3_0
  - gemfiles/Gemfile.rails3_1
  - gemfiles/Gemfile.rails3_2
